export default {
  style: {
    definitions: [
      { name: 'Looks like H2 <h2>', element: 'h2', classes: ['text-4xl'] },
      { name: 'Looks like H3 <h2>', element: 'h2', classes: ['text-3xl'] },
      { name: 'Looks like H4 <h2>', element: 'h2', classes: ['text-2xl'] },
      { name: 'Looks like H5 <h2>', element: 'h2', classes: ['text-xl'] },
      { name: 'Looks like H6 <h2>', element: 'h2', classes: ['text-lg'] },
      { name: 'Looks like H2 <h3>', element: 'h3', classes: ['text-4xl'] },
      { name: 'Looks like H3 <h3>', element: 'h3', classes: ['text-3xl'] },
      { name: 'Looks like H4 <h3>', element: 'h3', classes: ['text-2xl'] },
      { name: 'Looks like H5 <h3>', element: 'h3', classes: ['text-xl'] },
      { name: 'Looks like H6 <h3>', element: 'h3', classes: ['text-lg'] },
      { name: 'Looks like H2 <h4>', element: 'h4', classes: ['text-4xl'] },
      { name: 'Looks like H3 <h4>', element: 'h4', classes: ['text-3xl'] },
      { name: 'Looks like H4 <h4>', element: 'h4', classes: ['text-2xl'] },
      { name: 'Looks like H5 <h4>', element: 'h4', classes: ['text-xl'] },
      { name: 'Looks like H6 <h4>', element: 'h4', classes: ['text-lg'] },
      { name: 'Looks like H2 <h5>', element: 'h5', classes: ['text-4xl'] },
      { name: 'Looks like H3 <h5>', element: 'h5', classes: ['text-3xl'] },
      { name: 'Looks like H4 <h5>', element: 'h5', classes: ['text-2xl'] },
      { name: 'Looks like H5 <h5>', element: 'h5', classes: ['text-xl'] },
      { name: 'Looks like H6 <h5>', element: 'h5', classes: ['text-lg'] },
      { name: 'Looks like H2 <h6>', element: 'h6', classes: ['text-4xl'] },
      { name: 'Looks like H3 <h6>', element: 'h6', classes: ['text-3xl'] },
      { name: 'Looks like H4 <h6>', element: 'h6', classes: ['text-2xl'] },
      { name: 'Looks like H5 <h6>', element: 'h6', classes: ['text-xl'] },
      { name: 'Looks like H6 <h6>', element: 'h6', classes: ['text-lg'] },
      { name: 'Paragraph Small', element: 'p', classes: ['text-sm'] },
      { name: 'Paragraph Large', element: 'p', classes: ['text-lg'] },
      { name: 'Mark (red) <mark>', element: 'mark', classes: ['red'] },
      { name: 'Mark (green) <mark>', element: 'mark', classes: ['green'] },
      { name: 'Mark (yellow) <mark>', element: 'mark', classes: ['yellow'] },
      { name: 'Keyboard Shortcut <kbd>', element: 'kbd', classes: ['light'] },
      { name: 'Keyboard Shortcut (dark) <kbd>', element: 'kbd', classes: ['dark'] },
    ],
  },
};
