color: pink
fieldLayouts:
  b5f39594-4dfb-477b-a358-ea2dac368b7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T21:18:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 477b807f-d946-4570-832f-1c86b7121be4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T21:27:18+00:00'
            elementCondition: null
            fieldUid: 87410aa7-3cd4-4961-9533-6d4f246113b5 # Builder: Content Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1c4a7a8-6e2a-4e29-8db6-6ca411465b04
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5cb029e3-a009-451e-8ab8-a2a2dec9a3f5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 9a8fffce-3c28-4326-8f7a-e31d2f6cc04b # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 483ce826-3abf-48ac-8c95-5114bda99f30
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-05T06:03:05+00:00'
            elementCondition: null
            fieldUid: aa7883a4-2cce-4316-85f3-ec6ea59402ec # Spacing
            handle: spaceBetween
            includeInCards: false
            instructions: null
            label: 'Space Between'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83b19129-be5e-447a-b70a-07015f272028
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: aa7883a4-2cce-4316-85f3-ec6ea59402ec # Spacing
            handle: spacingYAxis
            includeInCards: false
            instructions: null
            label: 'Spacing Y-Axis'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2acb96f-9f12-4449-ad76-d024ad3d28ab
            userCondition: null
            warning: null
            width: 50
        name: Settings
        uid: 0e25f530-3ed7-4487-844d-d44d5422df0c
        userCondition: null
handle: blockSection
hasTitleField: false
icon: grid-2
name: Section
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
