color: green
description: null
fieldLayouts:
  7b6ace88-ae82-4caf-afe4-1650ce6e7ce3:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:243140b3-d692-4031-b56b-8a51521c3fae'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T22:02:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9add7508-89cd-4b19-b8e5-f6173a4ec371 # Rich Text
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 243140b3-d692-4031-b56b-8a51521c3fae
            userCondition: null
            warning: null
            width: 100
        name: Text
        uid: a7ac4d85-057b-421c-a16b-b382da491a30
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b81cb731-dd6f-4055-9c6d-2f076a727a27 # Image
            handle: null
            instructions: null
            label: Image
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab6dd79a-0d9c-4799-860a-01a7c242ba68
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62883121-63a2-4e5c-a6f3-4855cf64df2c # Image Ratio
            handle: null
            instructions: null
            label: 'Image Ratio'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04337482-6861-47b4-8a21-cd4447d746ab
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 210de09a-f6c8-42dd-b4d6-c1c00e7d0b82 # Image Position
            handle: null
            instructions: null
            label: 'Image Position'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ce2335a-ddf7-4a2f-a788-0c629ecec74b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T22:02:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 31947efb-fa8c-473c-9b01-bd36c8d70b68 # Lightswitch OFF
            handle: showCaption
            instructions: null
            label: 'Show Caption'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5c87ad3-30a4-42d6-bf64-9fd21c1e7259
            userCondition: null
            warning: null
            width: 50
        name: Image
        uid: 7931c967-9547-46fa-99e4-270c687a7cb3
        userCondition: null
    thumbFieldKey: 'layoutElement:ab6dd79a-0d9c-4799-860a-01a7c242ba68'
handle: block_textImage
hasTitleField: false
icon: table-columns
name: 'Text : Image'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
