color: green
description: null
fieldLayouts:
  12757233-a8be-4796-bed0-bdaffeb488ae:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:f7c03fb7-5b14-4971-a490-60532f436e6c'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T22:00:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9add7508-89cd-4b19-b8e5-f6173a4ec371 # Rich Text
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7c03fb7-5b14-4971-a490-60532f436e6c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f371c36b-db60-4c3f-a1dc-a3e11244e2ca
        userCondition: null
handle: block_text
hasTitleField: false
icon: font-case
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
