color: pink
fieldLayouts:
  251e7957-70a6-4f51-b158-0478e67df7ab:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T22:47:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d73e3100-f70d-4270-8455-591876d707ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T22:49:04+00:00'
            elementCondition: null
            fieldUid: 87410aa7-3cd4-4961-9533-6d4f246113b5 # Content Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa062f1a-027c-4b92-9a14-c28e39460463
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59acf730-63ce-4146-b27a-e9d7017e967a
        userCondition: null
handle: blockColumn
hasTitleField: false
icon: square
name: Column
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
