color: red
fieldLayouts:
  be62de4f-cc21-4603-aab3-8623d43b46ad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T19:47:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 11f6a034-44e7-434e-8035-8dbb7423fbb3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T21:13:37+00:00'
            elementCondition: null
            fieldUid: edfcb398-ef78-43ec-9434-d6405da2886e # Text Single
            handle: customTitle
            includeInCards: true
            instructions: null
            label: 'Custom Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c65cf828-a7a0-48ce-bd9f-2a985d1ae412
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T21:13:37+00:00'
            elementCondition: null
            fieldUid: 5af0a821-fa33-490a-9439-3193f439dd06 # Rich Text Simple
            handle: description
            includeInCards: true
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f674d204-6152-4ea6-8ffa-d252102a6225
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T21:13:37+00:00'
            elementCondition: null
            fieldUid: b81cb731-dd6f-4055-9c6d-2f076a727a27 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f06d8ad-dd7d-41a7-ae4a-8c9ec302a246
            userCondition: null
            warning: null
            width: 100
        name: Entry
        uid: 3314e7a8-7edd-461d-bdad-5a093d526ddd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T21:18:11+00:00'
            elementCondition: null
            fieldUid: 75f91f6f-fc53-49ad-bde0-365d6384b711 # Builder: Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 500cdedc-3d17-48dc-bc17-e290b0969045
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: baee5fce-39b4-49ec-8668-707dd127397f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: d29e8520-ab62-4c8f-bda2-61868797c1ca # SEOmatic
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fba6047-0faa-41d1-8404-16a9d9bfa56c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: c7d4e6c6-adcf-499a-97b1-2006cda02e10
        userCondition: null
handle: entryHome
hasTitleField: true
icon: memo
name: _Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
