isPublic: true
name: 'Public Schema'
scope:
  - 'sites.8153a2df-373f-4aac-9a92-d52292c9f1aa:read' # Baukasten
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.5d0f7961-203c-4008-a55a-6a7d35e7a37a:read' # Home
  - 'sections.e5172a18-ed16-4229-89ca-fc0dc776597a:read' # Error Pages
  - 'sections.3547e7b4-f3fb-4cf4-9d29-9f12dfa94594:read' # News
  - 'sections.b0207f48-be48-49ab-a759-1ff51f232df3:read' # Pages
  - 'nestedentryfields.9add7508-89cd-4b19-b8e5-f6173a4ec371:read' # Rich Text
  - 'nestedentryfields.5af0a821-fa33-490a-9439-3193f439dd06:read' # Rich Text Simple
  - 'nestedentryfields.f01420dc-b04a-4da5-9f17-6af2c1769bb7:read'
  - 'nestedentryfields.75f91f6f-fc53-49ad-bde0-365d6384b711:read' # Content
  - 'nestedentryfields.87410aa7-3cd4-4961-9533-6d4f246113b5:read' # Content Blocks
  - 'volumes.6c5fc0dd-cf56-48d8-8af8-88abe763b970:read' # Files
  - 'volumes.f1b38495-8096-48fa-9b78-0da345e3295c:read' # Images
  - 'volumes.77c74b5c-6bbb-41a7-b166-c6b158a3cc7f:read' # Template Images
  - 'volumes.8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6:read' # Users
  - 'usergroups.everyone:read'
  - 'navigationNavs.all:read'
  - 'navigationNavs.7eb1a718-0679-4fda-b656-9bfdf55a2025:read'
  - 'seomatic.all:read'
  - 'directive:parseRefs'
  - 'directive:transform'
