columnSuffix: null
handle: builder2Columns
instructions: null
name: 'Builder: 2 Columns'
searchable: true
settings:
  createButtonLabel: null
  entryTypes:
    - 09438ace-6245-4f84-aa58-228d00392a9a # Column
  includeTableView: true
  maxEntries: 2
  minEntries: 2
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
