columnSuffix: null
handle: builderContentBlocks
instructions: null
name: 'Builder: Content Blocks'
searchable: true
settings:
  createButtonLabel: 'Add block'
  entryTypes:
    - f3e1a215-a60f-4d6a-8897-e1a80a40c6cd # Code
    - 295738c1-951d-4b8c-b5cd-83d71a85d7e8 # Image
    - 5c9f2ce6-f780-4ea6-a50c-539a252aec94 # Images
    - baf82dc6-9e5a-4933-aa96-15eed58c888f # Links
    - fa02ff5a-1741-4417-8c8f-b72b954dd4fd # Quote
    - 92963d20-e763-4d2e-a367-9e543dfde522 # Spacer
    - 7b3b13e0-e20d-4d51-b0ae-832300f45234 # Text
    - 3497ad65-5e4c-43cb-b469-c3e4b3d80343 # Text : Image
    - 7b23a4a8-a6f8-43c4-b12c-326d089176ad # Video
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
