columnSuffix: null
handle: columnRatio
instructions: null
name: 'Column Ratio'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '50:50'
        -
          - value
          - '50_50'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '66:33'
        -
          - value
          - '66_33'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '33:66'
        -
          - value
          - '33_66'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
